"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$status\
[ ](fg:color_bg1 bg:color_aqua)\
$cmd_duration(bg:color_aqua)\
[](fg:color_aqua)\
$line_break\
[](color_bg1)\
$os\
$username\
[](fg:color_bg1 bg:color_blue)\
$directory\
[](fg:color_blue bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_aqua)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_aqua bg:color_bg1)\
$time\
[](fg:color_bg1)\
$line_break$character"""

palette = 'my_palette'


[palettes.my_palette]
color_fg0    = '#FFFCF0'
color_fg1    = '#100F0F'
color_bg1    = '#100F0F'
color_bg3    = '#54514D'
color_blue   = '#205EA6'
color_aqua   = '#24837B'
color_green  = '#66800B'
color_orange = '#d65d0e'
color_purple = '#A02F6F'
color_red    = '#AF3029'
color_yellow = '#AD8301'

[status]
disabled       = false
format         = '[$symbol $status( $common_meaning) ]($style)'
success_symbol = ""
symbol = "󱓇 "
success_style  = "bg:color_bg1 fg:color_green"
failure_style  = "bg:color_bg1 fg:color_red"

[cmd_duration]
min_time          = 0
show_milliseconds = true
style             = 'bg:color_aqua fg:color_fg0'
format            = '[took ]($style)[$duration](bold $style)'

[os]
disabled = false
style    = "bg:color_bg1 fg:color_fg0"

[os.symbols]
Windows          = "󰍲"
Ubuntu           = "󰕈"
SUSE             = ""
Raspbian         = "󰐿"
Mint             = "󰣭"
Macos            = "󰀵"
Manjaro          = ""
Linux            = "󰌽"
Gentoo           = "󰣨"
Fedora           = "󰣛"
Alpine           = ""
Amazon           = ""
Android          = ""
Arch             = "󰣇"
Artix            = "󰣇"
EndeavourOS      = ""
CentOS           = ""
Debian           = "󰣚"
Redhat           = "󱄛"
RedHatEnterprise = "󱄛"
Pop              = ""
NixOS            = ""

[username]
show_always = true
style_user  = "bg:color_bg1 fg:color_fg0"
style_root  = "bg:color_bg1 fg:color_fg0"
format      = '[ $user ]($style)'

[directory]
style             = "fg:color_fg0 bg:color_blue"
format            = "[   $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = "󰝚 "
"Pictures"  = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style  = "bg:color_yellow fg:color_fg1"
format = '[ $symbol $branch ]($style)'

[git_status]
style  = "bg:color_yellow fg:color_fg1"
format = '[($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[c]
symbol = " "
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[rust]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[golang]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[php]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[java]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[kotlin]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[haskell]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[python]
symbol = ""
style  = "bg:color_aqua"
format = '[[ $symbol( $version) ($virtualenv) ](fg:color_fg0 bg:color_aqua)]($style)'

[time]
disabled    = false
time_format = "%T"
style       = "bg:color_bg1"
format      = '[[   $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled                  = false
success_symbol            = '[](bold fg:color_green)'
error_symbol              = '[](bold fg:color_red)'
vimcmd_symbol             = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol     = '[](bold fg:color_purple)'
vimcmd_visual_symbol      = '[](bold fg:color_yellow)'
