---
title: This is a flowchart
---
flowchart LR
    pipe@{ shape: das, label: "All possibilities" }
    downward[\can be found/]
    docs[(in the docs)]

    link@{ shape: braces, label: "https://mermaid.ai/open-source/syntax/flowchart.html" }

    pipe --> downward
    downward --> docs
    docs --> link
%% sequenceDiagram
%%     Alice->>John: Hello John, how are you?
%%     John-->>Alice: Great!
%%     Alice-)John: See you later!
