[general]
live_config_reload = true

[font]
size = 14
[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "ZedMono Nerd Font Mono"  # My previous fond

[window]
blur        = true
decorations = "Buttonless" # For initial setup on macos "Full" (Shows the 3 window controlling buttons)
opacity     = 0.85

# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[colors.primary]

background        = "#ffffff"
foreground        = "#0e1116"
bright_foreground = "#0e1116"

[colors.cursor]

text   = "#ffffff"
cursor = "#0969da"

[colors.vi_mode_cursor]

text   = "CellBackground"
cursor = "CellForeground"

[colors.selection]

text       = "#0e1116"
background = "#ddf4ff"

[colors.normal]

black   = "#24292f"
red     = "#cf222e"
green   = "#116329"
yellow  = "#4d2d00"
blue    = "#0969da"
magenta = "#8250df"
cyan    = "#1b7c83"
white   = "#6e7781"

[colors.bright]

black   = "#57606a"
red     = "#a40e26"
green   = "#1a7f37"
yellow  = "#633c01"
blue    = "#218bff"
magenta = "#a475f9"
cyan    = "#3192aa"
white   = "#8c959f"

[colors.search.matches]

foreground = "#0e1116"
background = "#fff8c5"

[colors.search.focused_match]

foreground = "#ffffff"
background = "#0969da"

[colors.footer_bar]

background = "#f6f8fa"
foreground = "#0e1116"

[colors.hints.start]

foreground = "#ffffff"
background = "#0969da"

[colors.hints.end]

foreground = "#0969da"
background = "#ffffff"
