[general]
live_config_reload = true

[colors.normal]
black   = "#100F0F"
blue    = "#205EA6"
cyan    = "#24837B"
green   = "#66800B"
magenta = "#A02F6F"
red     = "#AF3029"
white   = "#FFFCF0"
yellow  = "#AD8301"

[colors.primary]
background        = "#282726"
bright_foreground = "#FFFCF0"
dim_foreground    = "#FFFCF0"
foreground        = "#FFFCF0"

[font]
size = 14
[font.normal]
family = "JetBrainsMono Nerd Font"
# family = "ZedMono Nerd Font Mono"  # My previous fond

[window]
blur        = true
decorations = "Buttonless" # For initial setup on macos "Full" (Shows the 3 window controlling buttons)
opacity     = 0.85
[colors.bright]
black   = "#100F0F"
blue    = "#4385BE"
cyan    = "#3AA99F"
green   = "#879A39"
magenta = "#CE5D97"
red     = "#D14D41"
white   = "#FFFCF0"
yellow  = "#D0A215"

[colors.cursor]
cursor = "#3AA99F"
text   = "#FFFCF0"

[colors.dim]
black   = "#100F0F"
blue    = "#205EA6"
cyan    = "#24837B"
green   = "#66800B"
magenta = "#A02F6F"
red     = "#AF3029"
white   = "#FFFCF0"
yellow  = "#AD8301"
